name: linkchecker

on: [push, pull_request]

jobs:
  Links:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2    

    - name: Run link checker
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: "./.github/workflows/check-markdown-links.json"
        folder-path: ".github" # Dummy entry until Github Action supports 'exclude' (scanner will find no .md files here)
        file-path: './essential-cardano-list.md' # Only scan files listed here
        use-quiet-mode: 'yes' # Specify yes to only show errors in output
